server:
  port: 31000
spring:
  application:
    name: controller-user
eureka:
  client:
    serviceUrl:
      defaultZone: http://pin100:pin100@127.0.0.1:30000/eureka/
ribbon:
  ReadTimeout: 60000
  ConnectTimeout: 60000
